language: rust
dist: xenial

cache:
  cargo: true

# https://gist.github.com/jkcclemens/000456ca646bd502cac0dbddcb8fa307
before_cache:
  - rm -rfv target/debug/incremental
  - rm -rfv target/debug/.fingerprint/blake2b*
  - rm -rfv target/debug/build/blake2b*
  - rm -rfv target/debug/deps/{libblake2b,blake2b}*
  - rm -rfv target/debug/{libblake2b,blake2b}*
  - cargo clean -p blake2b-py

matrix:
  fast_finish: true
  include:
    - os: linux
      rust: nightly
    - os: osx
      rust: nightly

install:
  - |
    if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      pip3 install --upgrade pip
      pip3 install maturin

      brew update

      # For python
      brew install openssl xz pyenv || true
      brew upgrade openssl xz pyenv || true

      brew switch pyenv 1.2.15

      pyenv install --skip-existing 3.8.0
      pyenv install --skip-existing 3.7.5
      pyenv install --skip-existing 3.6.9
    fi

script:
  - |
    if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      export PATH="$HOME/.pyenv/versions/3.6.9/bin:$PATH"
      export PATH="$HOME/.pyenv/versions/3.7.5/bin:$PATH"
      export PATH="$HOME/.pyenv/versions/3.8.0/bin:$PATH"

      maturin build --no-sdist -i python3.8
      maturin build --no-sdist -i python3.7
      maturin build --no-sdist -i python3.6
    fi
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      docker run --rm -v $(pwd):/io --entrypoint /bin/bash konstin2/maturin:master -c \
        'export PATH=/opt/python/cp38-cp38/bin/:$PATH
        rustup default nightly
        cd /io
        maturin build -i python3.8
        maturin build --no-sdist -i python3.7
        maturin build --no-sdist -i python3.6'
    fi

branches:
  only:
    # Pushes to the master branch
    - master
    # Match release tags with a regex
    - /^v\d+\.\d+\.\d+.*$/

notifications:
  email: false
