[package]
name = "blake2"
version = "0.1.0"
authors = ["David Sanders <davesque@gmail.com>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/davesque/blake2"
description = "Blake2 compression in Rust with Python bindings."

[dependencies]
pyo3 = "0.8"

[dev-dependencies]
hex = "0.4.0"
