[package]
name = "blake2"
version = "0.1.0"
authors = ["David Sanders <davesque@gmail.com>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/davesque/blake2"
description = "Blake2 compression in Rust with Python bindings."

[dev-dependencies]
pyo3 = "0.8"
hex = "0.4"
quickcheck = "0.9"
quickcheck_macros = "0.8"

[profile.dev]
overflow-checks = false

[profile.test]
overflow-checks = false
