version: 2.0

common: &common
  working_directory: ~/repo
  steps:
    - checkout
    - run:
        name: merge pull request base
        command: ./.circleci/merge_pr.sh
    - run:
        name: merge pull request base (2nd try)
        command: ./.circleci/merge_pr.sh
        when: on_fail
    - run:
        name: merge pull request base (3nd try)
        command: ./.circleci/merge_pr.sh
        when: on_fail
    - restore_cache:
        keys:
          - v4-cache-{{ .Environment.CIRCLE_JOB }}-{{ checksum "Cargo.toml" }}
    - run:
        name: setup nightly toolchain
        command: rustup install nightly && rustup default nightly
    - run:
        name: run tests
        command: make test test_against_python
    - save_cache:
        paths:
          - target
        key: v4-cache-{{ .Environment.CIRCLE_JOB }}-{{ checksum "Cargo.toml" }}

jobs:
  core:
    <<: *common
    docker:
      - image: davesque/rust-python
        environment:
          TOXENV: doctest
workflows:
  version: 2
  test:
    jobs:
      - core
