version: 2.0

common: &common
  working_directory: ~/repo
  docker:
    - image: davesque/rust-python:nightly-py37

jobs:
  core:
    <<: *common
    steps:
      - checkout
      - run:
          name: merge pull request base
          command: ./.circleci/merge_pr.sh
      - run:
          name: merge pull request base (2nd try)
          command: ./.circleci/merge_pr.sh
          when: on_fail
      - run:
          name: merge pull request base (3nd try)
          command: ./.circleci/merge_pr.sh
          when: on_fail
      - restore_cache:
          keys:
            - v4-cache-{{ .Environment.CIRCLE_JOB }}-{{ checksum "Cargo.toml" }}
      - run:
          name: run tests
          command: make test_rust
      - save_cache:
          paths:
            - target
          key: v4-cache-{{ .Environment.CIRCLE_JOB }}-{{ checksum "Cargo.toml" }}

  py36-integration:
    <<: *common
    docker:
      - image: davesque/rust-python:nightly-py36
    steps:
      - checkout
      - run:
          name: merge pull request base
          command: ./.circleci/merge_pr.sh
      - run:
          name: merge pull request base (2nd try)
          command: ./.circleci/merge_pr.sh
          when: on_fail
      - run:
          name: merge pull request base (3nd try)
          command: ./.circleci/merge_pr.sh
          when: on_fail
      - restore_cache:
          keys:
            - v4-cache-{{ .Environment.CIRCLE_JOB }}-{{ checksum "Cargo.toml" }}
      - run:
          name: run tests
          command: pip install -r requirements-dev.txt && pytest
      - save_cache:
          paths:
            - target
          key: v4-cache-{{ .Environment.CIRCLE_JOB }}-{{ checksum "Cargo.toml" }}

workflows:
  version: 2
  test:
    jobs:
      - core
      - py36-integration
